accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('signup',views.signup_view,name="signup"),
	path('login',views.login_view,name="login"),
	path('logout',views.logout_view,name='logout'),

]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('',views.article_list,name="list"),

   	path('create',views.article_create,name="create"),

    path('<slug:slug>/',views.article_detail, name="detail"),

    path('comment/<int:pk>/',views.create_comment, name = "comment"),

]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('about/',views.about),
    path('',article_views.article_list, name='home'),
    path('articles/',include('articles.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=100)
	slug  = models.SlugField()
	body  = models.TextField()
	date  = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default="default.png", blank=True) 
	author = models.ForeignKey(User,on_delete=models.CASCADE, default=None)

	# add in thumbnail
	# add in author later

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + '...'	


class Comment(models.Model):
    post = models.ForeignKey('articles.Article', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text	

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article 
		fields = ['title','body','slug','thumb']


class CommentForm(forms.ModelForm):

    class Meta:
        model = models.Comment
        fields = ['text']

accounts/views.py
from django.shortcuts import render,redirect, reverse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
	if request.method =='POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request,user)
			# log the user in
			return redirect('articles:list')

	else:
		form = UserCreationForm()	
	return render(request,'accounts/signup.html',{'form':form })


def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log in the user
			user = form.get_user()
			login(request, user)

			if 'next' in request.POST:
				return redirect(request.POST.get('next'))

			else:	
				return redirect('articles:list')

	else:
		form = AuthenticationForm()
		
	return render(request,'accounts/login.html',{'form':form})	

def logout_view(request):
	if request.method =='POST':
		logout(request)
		return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Comment
# Create your views here.

def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request,'articles/articles_list.html',{'articles':articles})


def article_detail(request, slug):
	#return HttpResponse(slug)
	article = Article.objects.get(slug =slug)
	comments = Comment.objects.filter(post=article).order_by('-created_date')
	print(comments)
	return render(request,'articles/article_detail.html',{'article':article,'comments':comments})

@login_required(login_url="/accounts/login")

def article_create(request):
	if request.method =='POST':
		form = forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			# save article to DB
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')


	else:
		form = forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})	



def create_comment(request, pk):

	if request.method == 'POST':
		form = forms.CommentForm(request.POST)	
		
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.post_id = pk
			instance.save()
			article = Article.objects.get(pk = pk)
			
			
		#return render(request,'articles/create_comment.html', { 'article_id': pk })
		return redirect('/articles/'+str(article.slug))
	
	
	else:
		print("PK: ", pk)
		return render(request,'articles/create_comment.html', { 'article_id': pk })

	

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
	#return HttpResponse("Home")
	return render(request,'homepage.html')

def about(request):
	#return HttpResponse("about Haripal")
	return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}


{% block content %}
<h1>Login</h1>  
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{request.GET.next}}">
		{% endif %}

	<input type="submit" name="Login">
	

</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}


{% block content %}
<h1>Signup</h1>  
<form class="site-form" action="/accounts/signup" method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<input type="submit" name="Signup">
	

</form>

{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}


{% block content %}

	<div class="create-article">
		<h2>Create an awesome new article</h2>
		<form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" name="" value="Create">
		</form>
	</div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}


{% block content %}

<div class="article-detail">
	<div class="article">
		<img src="{{ article.thumb.url}}"/>
		<h2>{{ article.title }}</h2>
		<p>{{ article.body}}</p>
		<p>{{article.date}}</p>	
	</div>
</div>

<p>Write a comment</p>

<br>
<br>

<a class="btn btn-default" href="{% url 'articles:comment' pk=article.pk %}">Add comment</a>


{% for comment in comments %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}


<hr>


{% endblock %}

articles/templates/articles/articles_list.html
{% extends 'base_layout.html'%}


{% block content%}

	<h1>Article List</h1>
	<div class="articles">
		{% for article in articles%}

			<div class = "article">
				<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
				<p>{{article.snippet}}</p>
				<p>{{article.date}}</p>
				<p class="author">Added by {{article.author.username}}</p>
			</div>



		


		{% endfor%}

 {% endblock %}	

articles/templates/articles/create_comment.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form" action="{% url 'articles:comment' pk=article_id %}">
    	{% csrf_token %}
        <input type="text" name="text"><br><br><br><br>
        <button type="submit" class="save btn btn-default" value="submit">Send</button>
    </form>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>About</title>
</head>
<body>
	<h1>About us</h1>
	<p>I like Django, by Haripal</p> 

</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Articles</title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
	<header class="wrapper">
	
		<h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" height="170px" width="170px"></a></h1>

			<nav>
				<ul>
					{% if user.is_authenticated %}
					<li>
						<form class="logout-link" method="POST" action="{% url 'accounts:logout'%}">
						{% csrf_token %}
						<button type="submit">Logout</button>
						</form>
						</li>
						<li> <a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
						{% else %}
						 
							<li><a href="{% url 'accounts:login' %}">Login</a></li>
							<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
						{% endif %}
					<ul>
				</nav>
		</header>
		<div class="wrapper">
		{% block content %}
		{% endblock %}
	</div>


	</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Homepage</title>
</head>
<body>
	<h1>This is the homepage</h1>
	<p>Welcome to Djangonautic</p> 

</body>
</html>